# Generated by Django 5.0.6 on 2024-07-04 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.role"
            ),
        ),
    ]
