# Generated by Django 5.0.6 on 2024-07-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
    ]
