# Generated by Django 5.0.6 on 2024-07-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schools",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
